#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Your Name | Course: Open Source Software
# Purpose: Asks user 3 questions interactively and generates
#          a personalised open source philosophy statement,
#          then saves it to a text file

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_output.txt"

echo "=========================================="
echo " Open Source Manifesto Generator"
echo "=========================================="
echo ""

read -p "1. Name one open source tool you use every day: " TOOL
read -p "2. In one word, what does freedom mean to you: " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

echo ""
echo "Generating your manifesto..."
echo ""

MANIFESTO="Open Source Manifesto — $DATE

I believe in the power of open source software. Every day I use $TOOL,
a tool built freely and shared openly by a global community of developers.
To me, freedom in software means $FREEDOM — the ability to use, study,
modify and distribute without restriction.

If I could build anything and share it freely with the world, it would be
$BUILD. Not for profit, not for control, but because the best software
is built when knowledge is shared rather than locked away.

Open source is not just a licensing model. It is a philosophy — one that
believes tools should serve people, not the other way around.

— Generated by Open Source Audit Script 5"

echo "$MANIFESTO" > "$OUTPUT"

echo "=========================================="
cat "$OUTPUT"
echo "=========================================="
echo ""
echo "Manifesto saved to $OUTPUT"
```